### ISSUE TITLE
Unit Cards

### ISSUE THREAD

**Issue by im-mortal** [Warhammer-Mods/arkhan_the_black_expanded#1]
- [x] Warhammer-Mods/arkhan_stevie#42
- [x] Warhammer-Mods/arkhan_stevie#43
- [x] Warhammer-Mods/arkhan_stevie#44
- [ ] Zombie Pirate Gunnery Mob
    `steve_ark_zmb_gunner_mob`
- [ ] Zombie Pirate Deckhands Mob (Polearms)
    `steve_ark_zmb_halberd`
- [ ] Zombie Pirate Gunnery Mob (Handguns)
    `steve_ark_zmb_handgunner_mob`
- [ ] Zombie Pirate Deckhands Mob
    `steve_ark_zmb`
- [ ] Rotting Prometheans Gunnery Mob
    `steve_ark_prometheans_gunnery_mob`
- [ ] Rotting Leviathan
    `steve_ark_rotting_leviathan`
- [ ] Vergheists
    `steve_ark_vargheist`
    ![Vergheists](../blob/develop/ui/units/icons/steve_ark_vargheist.png?raw=true)
- [ ] Skeleton Horsemen Archers
    `xereus_tmb_cav_skeleton_horsemen_archers`    
- [ ] Dire Wolves
    `wh2_dlc09_tmb_dire_wolves`
    ![Dire Wolves](../blob/develop/ui/units/icons/wh2_dlc09_tmb_dire_wolves.png?raw=true)
- [ ] Fell Bats
    `wh2_dlc09_tmb_fell_bats`
    ![Fell Bats](../blob/develop/ui/units/icons/wh2_dlc09_tmb_fell_bats.png?raw=true)
- [x] Warhammer-Mods/arkhan_stevie#37
    ![Necrosphinx](../blob/develop/ui/units/icons/xereus_tmb_mon_necrosphinx.png?raw=true)
- [x] Warhammer-Mods/arkhan_stevie#36
    ![Hierotitan](../blob/develop/ui/units/icons/xereus_tmb_mon_hierotitan.png?raw=true)
- [x] Khemrian Warsphinx
    `xereus_tmb_veh_khemrian_warsphinx`
- [x] Hexwraiths
    `wh2_dlc09_tmb_cav_hexwraiths.png`
    ![Hexwraiths](../blob/develop/ui/units/icons/wh2_dlc09_tmb_cav_hexwraiths.png?raw=true)
- [x] Mournguls
    `xereus_tmb_mon_mournguls`
- [x] Cairn Wraiths
    `steve_ark_cairn_wraith`
    ![Cairn Wraiths](../blob/develop/ui/units/icons/steve_ark_cairn_wraith.png?raw=true)
- [x] Terrorgheist
    `steve_ark_terrorgheist`
    ![Terrorgheist](../blob/develop/ui/units/icons/steve_ark_terrorgheist.png?raw=true)
- [x] Crypt Ghouls
    `wh2_dlc09_tmb_crypt_ghouls`
    ![Crypt Ghouls](../blob/develop/ui/units/icons/wh2_dlc09_tmb_crypt_ghouls.png?raw=true)
- [x] Crypt Horrors
    `steve_ark_crypt_horror`
    ![Crypt Horrors](../blob/develop/ui/units/icons/steve_ark_crypt_horror.png?raw=true)
- [x] Tomb Guard
    `stephen_tmb_inf_tomb_guard`
    ![Tomb Guard](../blob/develop/ui/units/icons/stephen_tmb_inf_tomb_guard.png?raw=true)
- [x] Tomb Guard (Halberds)
    `stephen_tmb_inf_tomb_guard_halberd`
    ![Tomb Guard (Halberds)](../blob/develop/ui/units/icons/stephen_tmb_inf_tomb_guard_halberd.png?raw=true)
- [x] Screaming Skull Catapult
    `stephen_tmb_art_screaming_skull_catapult`
    ![Screaming Skull Catapult](../blob/develop/ui/units/icons/stephen_tmb_art_screaming_skull_catapult.png?raw=true)
- [x] Ushabti
    `steve_ark_tmb_mon_ushabti`
    ![Ushabti](../blob/develop/ui/units/icons/steve_ark_tmb_mon_ushabti.png?raw=true)
- [x] Ushabti (Great Bows)
    `steve_ark_tmb_mon_ushabti_great`
    ![Ushabti (Great Bows)](../blob/develop/ui/units/icons/steve_ark_tmb_mon_ushabti_great.png?raw=true)
- [x] Zombie Dragon
    `steve_ark_zombie_dragon`
    ![Zombie Dragon](../blob/develop/ui/units/icons/steve_ark_zombie_dragon.png?raw=true)
- [x] Zombies
    `steve_ark_zmb_summon`
    ![Zombies](../blob/develop/ui/units/icons/steve_ark_zmb_summon.png?raw=true)
- [x] Mortis Engine
  `steve_ark_mortis_engine`
   ![Mortis Engine](../blob/develop/ui/units/icons/steve_ark_mortis_engine.png?raw=true)
- [x] Grave Guard
    `steve_ark_grave_guard`
    ![Grave Guard](../blob/develop/ui/units/icons/steve_ark_grave_guard.png?raw=true)
- [x] Grave Guard (Great Weapons)
    `steve_ark_grave_guard_great`
    ![Grave Guard (Great Weapons)
](../blob/develop/ui/units/icons/steve_ark_grave_guard_great.png?raw=true)
- [x] Nagashizzar Guard
    `steve_ark_nagashizzar_guard`
    ![Nagashizzar Guard](../blob/develop/ui/units/icons/steve_ark_nagashizzar_guard.png?raw=true)
- [x] Skeleton Archers
    `steve_ark_skeleton_archers`
    ![Skeleton Archers](../blob/develop/ui/units/icons/steve_ark_skeleton_archers.png?raw=true)
- [x] Skeleton Spearmen
    `steve_ark_skeleton_spearmen`
    ![Skeleton Spearmen](../blob/develop/ui/units/icons/steve_ark_skeleton_spearmen.png?raw=true)
- [x] Skeleton Warriors
    `steve_ark_skeleton_warriors`
    ![Skeleton Warriors](../blob/develop/ui/units/icons/steve_ark_skeleton_warriors.png?raw=true)
- [x] Warhammer-Mods/arkhan_stevie#34 
    ![Skeleton Warriors](../blob/develop/ui/units/icons/xereus_tmb_inf_nehekaran_warriors.png?raw=true)

---

- [x] Liche Priest (Lore of Vampires)
  - [x] `tmb_cha_liche_priest_vampire_1`
    ![Liche Priest 1](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/tmb_cha_liche_priest_vampire_1.png?raw=true)
  - [x] `tmb_cha_liche_priest_vampire_2`
    ![Liche Priest 2](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/tmb_cha_liche_priest_vampire_2.png?raw=true)
  - [x] `tmb_cha_liche_priest_vampire_3`
    ![Liche Priest 3](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/tmb_cha_liche_priest_vampire_3.png?raw=true)
  - [x] `tmb_cha_liche_priest_vampire_4`
    ![Liche Priest 4](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/tmb_cha_liche_priest_vampire_4.png?raw=true)
  - [x] `tmb_cha_liche_priest_vampire_5`
    ![Liche Priest 5](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/tmb_cha_liche_priest_vampire_5.png?raw=true)

- [ ] Wight King
  - [ ] `stephen_wight_king_sword_campaign_01_0`
  - [ ] `stephen_wight_king_sword_campaign_02_0`
  - [ ] `stephen_wight_king_sword_campaign_03_0`
  - [ ] `stephen_wight_king_sword_campaign_04_0`
  
 - [ ] Necrotect
  - [ ] `xereus_tmb_cha_necrotect_vampires_1`
  - [ ] `xereus_tmb_cha_necrotect_vampires_2`
  - [ ] `xereus_tmb_cha_necrotect_vampires_3`
  - [ ] `xereus_tmb_cha_necrotect_vampires_4`
  
 - [ ] Tomb Prince
  - [ ] `xereus_tmb_cha_tomb_prince_vampires_1`
  - [ ] `xereus_tmb_cha_tomb_prince_vampires_2`
  - [ ] `xereus_tmb_cha_tomb_prince_vampires_3`
  - [ ] `xereus_tmb_cha_tomb_prince_vampires_4`
  - [ ] `xereus_tmb_cha_tomb_prince_vampires_5`

- [x] Tomb King
  - [x] `stephen_ch_tomb_king_campaign_01_0`
    ![Tomb King 1](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/stephen_ch_tomb_king_campaign_01_0.png?raw=true)
  - [x] `stephen_ch_tomb_king_campaign_02_0`
    ![Tomb King 2](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/stephen_ch_tomb_king_campaign_02_0.png?raw=true)
  - [x] `stephen_ch_tomb_king_campaign_03_0`
    ![Tomb King 3](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/stephen_ch_tomb_king_campaign_03_0.png?raw=true)
  - [x] `stephen_ch_tomb_king_campaign_04_0`
    ![Tomb King 4](../blob/develop/ui/portraits/units/wh2_dlc09_tmb_tomb_kings/stephen_ch_tomb_king_campaign_04_0.png?raw=true)

**Comment by im-mortal** [comment]
@Zalbardeon I'd like to kindly ask you to curate this list of unit cards that you want me to update. If possible, please also include the id of the unit.

**Comment by im-mortal** [comment]
I’ve added `wh2_dlc09_tmb_skeleton_archers` in 27c4979c094100249c8683593851889c52e86c00 but not sure if it’s the right id since it should probably use mod custom key instead.

**Comment by Zalbardeon** [comment]
Ah, yes, my bad! I'll correct it now!

**Comment by Zalbardeon** [comment]
Unit cards updated with the correct ID's!

**Comment by Zalbardeon** [comment]
After the Zombie Dragon unit card has been updated and you're happy with it, you could always start on the Ushabti & Ushabti (Great Bows) as I'd like to add them to the Necropolis building chain, as they're going to be the guardians of those dark halls. I feel like Arkhan should get a unique looking version of them.

**Comment by im-mortal** [comment]
> Ushabti & Ushabti (Great Bows)

~~Sure thing, but what about their respective IDs, please?~~
Scrap that, I'm blind. Will do.

**Comment by Zalbardeon** [comment]
New Units Added

xereus_tmb_cav_necropolis_knights_1
xereus_tmb_cav_necropolis_knights_2
xereus_tmb_mon_tomb_scorpion

**Comment by Zalbardeon** [comment]
![Image](https://user-images.githubusercontent.com/83952869/182692189-67ed07b7-4a6d-4c4d-aa29-921f6ffa1d9f.png)
![Image](https://user-images.githubusercontent.com/83952869/182692190-9c6cb295-4096-4663-8c67-5f7d5a79ecff.png)
![Image](https://user-images.githubusercontent.com/83952869/182692188-4a2c5571-103c-4cab-a97a-92f1236f1980.png)

**Comment by Zalbardeon** [comment]
New units added:

xereus_tmb_cha_necrotect_vampires_1
xereus_tmb_cha_necrotect_vampires_2
xereus_tmb_cha_necrotect_vampires_3
xereus_tmb_cha_necrotect_vampires_4

![tmb_necrotect_campaign_01_0](https://user-images.githubusercontent.com/83952869/184500317-8e314cdd-5a5e-44b4-b7e4-b0fcbd5d50c9.png)
![tmb_necrotect_campaign_02_0](https://user-images.githubusercontent.com/83952869/184500318-96f54ada-ee19-4fb7-9aa5-90f0657751fd.png)
![tmb_necrotect_campaign_03_0](https://user-images.githubusercontent.com/83952869/184500319-dc2e7759-3907-40ad-b448-7719730fcac3.png)
![tmb_necrotect_campaign_04_0](https://user-images.githubusercontent.com/83952869/184500321-399865d2-f709-48ab-960e-df330a2c9682.png)

![tmb_necrotect_campaign_01_0](https://user-images.githubusercontent.com/83952869/184500345-5e937cf8-eaf4-45d7-bcb8-14d4f887ddaf.png)
![tmb_necrotect_campaign_02_0](https://user-images.githubusercontent.com/83952869/184500347-9960f0c6-d0a6-4fa2-8b22-7ea25c9b34a0.png)
![tmb_necrotect_campaign_03_0](https://user-images.githubusercontent.com/83952869/184500348-57d9d070-7a59-4f5a-9890-4f3be88130f7.png)
![tmb_necrotect_campaign_04_0](https://user-images.githubusercontent.com/83952869/184500349-62a7a26e-d4a2-492f-94fb-4779820f626c.png)

**Comment by Zalbardeon** [comment]
New Units Added:

xereus_tmb_cha_tomb_prince_vampires_1
xereus_tmb_cha_tomb_prince_vampires_2
xereus_tmb_cha_tomb_prince_vampires_3
xereus_tmb_cha_tomb_prince_vampires_4
xereus_tmb_cha_tomb_prince_vampires_5

![tmb_ch_tomb_prince_campaign_03_0](https://user-images.githubusercontent.com/83952869/184500566-1f4a9073-f7f0-4267-b70b-387f9141015a.png)
![tmb_ch_tomb_prince_campaign_04_0](https://user-images.githubusercontent.com/83952869/184500568-693599aa-dff1-469d-856d-24fda59e40d5.png)
![tmb_ch_tomb_prince_campaign_05_0](https://user-images.githubusercontent.com/83952869/184500569-135813e0-10fa-4637-a77a-dbc0c85a6e6d.png)
![tmb_ch_tomb_prince_campaign_01_0](https://user-images.githubusercontent.com/83952869/184500571-6a0962d1-d0c4-4abe-88ef-7239e5deb0c2.png)
![tmb_ch_tomb_prince_campaign_02_0](https://user-images.githubusercontent.com/83952869/184500572-cbbfc843-886d-43fe-b60d-3def90570071.png)

![tmb_ch_tomb_prince_campaign_01_0](https://user-images.githubusercontent.com/83952869/184500578-84de9dfb-670f-4bc8-ad45-f5929dba1c94.png)
![tmb_ch_tomb_prince_campaign_02_0](https://user-images.githubusercontent.com/83952869/184500580-d62eb7bd-b691-4d0a-88f6-1ba3e0178626.png)
![tmb_ch_tomb_prince_campaign_03_0](https://user-images.githubusercontent.com/83952869/184500582-91fc6993-826c-4314-b6e8-66ec5c32acab.png)
![tmb_ch_tomb_prince_campaign_04_0](https://user-images.githubusercontent.com/83952869/184500583-b8e074a5-4780-4dc9-8f08-f4707effcaa7.png)
![tmb_ch_tomb_prince_campaign_05_0](https://user-images.githubusercontent.com/83952869/184500585-45581d12-a9e0-4fc7-9c5f-04e23d056ba2.png)

**Comment by im-mortal** [comment]
How vampiric, if ever, should these unit cards and portholes, both for necrotects and tomb princes, appear? I’m speaking about the volumes of shades of red vs. Nagash Purple.

Also, do 120×240 px. versions of heroes’ unit cards exist? I vaguely remember that they do not, but I’m quite happy to be proven wrong.

**Comment by Zalbardeon** [comment]
I'm thinking more purple with a hint or tint of red. In fact, Tomb Princes can probably use a dash more red, and Necrotects a dash of some green as well.

From what I can see, I can't find a 120×240 px version of the unit card.

**Comment by im-mortal** [comment]
Noted, thank you!

I was thinking about predominantly red for a change, but I also understand I should keep the general color palette more or less in line with other unit cards.

**Comment by Zalbardeon** [comment]
There's no harm in variants that don't quite follow the trend of the other unity cards. Variety is always good!

**Comment by Zalbardeon** [comment]
New units added:

xereus_tmb_veh_khemrian_warsphinx
xereus_tmb_cav_skeleton_horsemen_archers

![wh2_dlc09_tmb_warsphinx](https://user-images.githubusercontent.com/83952869/187027202-8897cf23-dcc1-4a34-b3cf-08fda8dcaf88.png)
![wh2_dlc09_tmb_skeleton_horsemen_archers](https://user-images.githubusercontent.com/83952869/187027283-c01c6aa1-fd63-4c82-bd5a-31d93365effb.png)

**Comment by Zalbardeon** [comment]
New units added:

xereus_tmb_mon_mournguls

![wh2_dlc11_cst_mournguls](https://user-images.githubusercontent.com/83952869/197392834-e5f82991-0d5f-4ffa-804b-d71ecfe12c3e.png)
![wh2_dlc11_cst_mournguls](https://user-images.githubusercontent.com/83952869/197392837-dfe18d96-6f6e-4849-a0aa-bf0c2c05ae47.png)

**Comment by Zalbardeon** [comment]
xereus_tmb_mon_bone_giant

![wh2_pro06_tmb_bone_giant](https://user-images.githubusercontent.com/83952869/206910764-caca5002-8c0d-4c1f-9d21-13bd7b238e16.png)
![wh2_pro06_tmb_bone_giant](https://user-images.githubusercontent.com/83952869/206910772-3e11383c-f6ea-4cfe-9616-3db552eb5e0e.png)

**Comment by Zalbardeon** [comment]
xereus_tmb_mon_sepulchral_stalkers

![wh2_dlc09_tmb_sepulchral_stalkers](https://user-images.githubusercontent.com/83952869/206910862-fed93193-2f25-4913-bb94-8af491793d55.png)
![wh2_dlc09_tmb_sepulchral_stalkers](https://user-images.githubusercontent.com/83952869/206910868-93568444-c959-4e4a-bde5-daf7c17472b7.png)
